config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tasks#index'

  resources :tasks do
    put :complete, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  PRIORITIES = [
    ['Later', 1],
    ['Next', 2],
    ['Now', 3]
  ]

  def complete!
    if self.completed == false
      self.completed = true
      save
    else
      self.completed = false
      save
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  self.primary_key = :id

  validates_presence_of :first_name, :last_name, :email, :password

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
      @tasks = Task.all
      if user_signed_in?
        @uncompleted_tasks = current_user.tasks.where(completed: false).order('priority DESC')
        @completed_tasks = current_user.tasks.where(completed: true).order('updated_at')
      end
  end

  def new
    build_task
  end

  def edit
    task
  end

  def create
    create_task
    redirect_to tasks_path
  end

  def complete
    complete_task
    redirect_to tasks_path
  end

  def update
    update_task
    redirect_to tasks_path
  end

  def destroy
    destroy_task
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(
      :title, :description, :priority, :due_date, :completed, :user_id
    )
  end

  def task
    @task ||= current_user.tasks.find(params[:id])
  end

  def build_task
    @task = current_user.tasks.new
  end

  def create_task
    @task = current_user.tasks.new task_params
    @task.save
  end

  def complete_task
    task.complete!
  end

  def update_task
    task.update(task_params)
  end

  def destroy_task
    task.destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav role="navigation" class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header navbar-left pull-left">
          <a class="navbar-brand">Task Manager</a>
        </div>
        <div class="navbar-header navbar-right pull-right">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><%= render 'devise/menu/registration_items' %></li>
            <li class="active"><%= render 'devise/menu/login_items' %></li>
          </ul>
        </div>
    </nav>

    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |type, msg| %>
          <% if type == "notice" %>
            <div class="alert alert-success">
          <% elsif type == "alert" %>
            <div class="alert alert-danger">
          <% else %>
            <div class='alert alert-<%= "#{type}" %>'>
          <% end %>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <ul>
            <li>
              <%= msg %>
            </li>
          </ul>
        <% end %>
        </div></div></div>
      </div>
    </div>

    <div class="container"><div class="row"><%= yield %></div></div>

  </body>
</html>

app/views/tasks/_form.html.erb
<div class="col-md-6">
  <%= simple_form_for @task do |f| %>
    <p><%= f.input :title, input_html: { :style=> 'width: 50%;'}%></p>
    <p><%= f.input :description, :as => :text, input_html: { :style=> 'width: 50%;'}%></p>
    <%= f.label "Priority"%>
    <p><%= f.select :priority, Task::PRIORITIES %></p>
    <p><%= f.input :due_date, as: :date, html5: true, input_html: { :style=> 'width: 50%;'}%></p>
    <p><%= f.input :completed%></p>
    <p><%= f.button :submit%></p>
  <%end%>
</div>

app/views/tasks/_task.html.erb
<div class="task priority_<%= task.priority %> completed_<%= task.completed %>">
  <p>
    <span class="title"><%=task.title%></span>
    <% if task.completed == false %>
      <%= link_to content_tag('span', '', class: 'fa fa-square-o'), complete_task_path(task), data: {method: :put}, class: 'action' %>
    <% else %>
      <%= link_to content_tag('span', '', class: 'fa fa-check-square-o'), complete_task_path(task), data: {method: :put}, class: 'action' %>
    <% end %>
    <%= link_to content_tag('span', '', class: 'fa fa-trash'), task, method: :delete, class: 'action' %>
    <%= link_to content_tag('span', '', class: 'fa fa-pencil'), edit_task_path(task), class: 'action' %>
  </p>
</div>

app/views/tasks/complete.html.erb
<h1>Tasks#complete</h1>
<p>Find me in app/views/tasks/complete.html.erb</p>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<div class="col-md-12">
  <h1>Edit task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>
<div class="col-md-12">
  <h1>My tasks</h1>

  <div class="buffer-top">
    <%= link_to "New task", new_task_path, class: 'btn btn-primary' %>
  </div>

  <div class="buffer-top">
    <% @uncompleted_tasks.each do |task| %>
      <%= render partial: 'task', object: task%>
    <%end%>

    <hr style="background-color: #C8C8C8; color: #C8C8C8;"/>

    <% @completed_tasks.each do |task| %>
      <%= render partial: 'task', object: task%>
    <%end%>
  </div>
</div>
<% else %>

<% end %>

app/views/tasks/new.html.erb
<div class="col-md-12">
  <h1>New task</h1>
</div>

<%= render 'form' %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>